spring:
  profiles:
    active: dev
#eureka:
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 10000
#  client:
#    register-with-eureka: false
#    fetch-register: false
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 10
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间
#    lease-expiration-duration-in-seconds: 30
    #表示eureka client发送心跳给server端的频率